name             'OpenSips'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures OpenSips'
long_description 'Installs/Configures OpenSips'
version          '0.1.0'

depends          'apt'
depends          'users'
